[WIP] Test templates management
ASbeletsky/LMS pull request #49
Opened 2018-07-20 11:38 UTC by Tirraon

Issue #8
Продолжая план https://github.com/ASbeletsky/LMS/issues/8#issuecomment-405535330

- [ ] Добавление новых уровней
- [ ] Добавить тестов для проверки уровней
- [ ] Не работает сохранение в базе выбранных категорий\типов уровней

2018-07-20 11:39 UTC, Tirraon commented
Мерж с дева сделаю в конце. 
Как минимум, после надо будет добавить атрибуты авторизации.

2018-07-20 22:51 UTC, Tirraon commented on LMS.Admin.Web/Controllers/TestTemplateController.cs
> +            var template = TempData["EditTemplate" + id] is string templateStr
По сути TempData тут нужен только для удобства, чтобы мы могли сделать редирект на GET edit с понятным адресом, а не сидеть после добавления уровня на POST testtemplate/newlevel. Плюс можно обновлять страницу без просьбы повторной отправки формы от браузера.

2018-07-20 23:58 UTC, Tirraon commented
@ASbeletsky 
По поводу "Не работает редактирование в базе выбранных категорий\типов уровней"
Это основной тормоз сейчас.
Есть модель вида:
TestTemplate:
-List<TestTemplateLevel>
-- Filter
--- List<LevelTaskType>
--- List<LevelCategory>
В Update репозитория они успешно доходят после всех изменений во вью, ничего не теряя, но после - LevelTaskType и LevelCategory полностью игнорируются (остаются старые значения).
Получилось частично заставить работать, пробегая по всем уровням и по всем таскам/категориям в них, вручную добавляя новые/удаляя старые значения, завтра продолжу в этом направлении. 
Но почему-то мне кажется, что должен быть нормальный способ. [Но не факт](https://stackoverflow.com/questions/27176014/how-to-add-update-child-entities-when-updating-a-parent-entity-in-ef)

2018-07-21 11:21 UTC, Tirraon commented on LMS.Entities/TestTemplateLevel.cs
> +        public int TestTemplateLevelId { get; set; }
*TestTemplateId

2018-07-21 19:35 UTC, Tirraon commented
@ASbeletsky 
Готово.
Вроде бы никаких проблем не осталось.
Сомнительное место с TestTemplateRepository.Update, но више уже описывать проблему - не удаляет уровни и не обновляет связанные списки в элементах связанных списоков (типы и категории уровней). Тот код выглядит как костыль, но рабочий.
На счет валидации: она есть, но сайт не запрещает сделать, например, 120 суммарных баллов, хоть и напишет об этом. Или нужно запретить?

Есть мысли о обновлении менеджмента тасков, в том числе обновить слайдеры, добавить цифры текущих значений и т.д.... Но это, как я понимаю, лучше в будущем в отдельной задаче, возможно с форматированием?

![gif](https://user-images.githubusercontent.com/3163374/43039433-9b7a018c-8d35-11e8-8b24-4c131f52be71.gif)

2018-07-22 21:26 UTC, ASbeletsky requested changes

2018-07-22 22:15 UTC, Tirraon commented on LMS.Admin.Web/wwwroot/js/testTemplate.js
> +            500);
Иначе при каждом движении слайдера отправляется запрос на сервер. В итоге получается спам. 
Если добавить таймаут - запросы не отправляются, пока не пройдёт пол секунды после последнего изменения.

2018-07-22 22:48 UTC, Tirraon commented on LMS.Dto/TestTemplateDTO.cs
> +        public const int MaxTaskPerLevelCount = 30;
50?
100?

2018-07-22 22:54 UTC, Tirraon commented on LMS.Data/Repositories/TestTemplateRepository.cs
> +            return GetAllQuery();
Сделаю, но почему?
Я думал, что лучше вообще IQueryable возвращать из репозиториев, чтобы запросы генерировались более оптимальные с кодом из бизнес слоя.
Или расчет на то, что нужно оптимально генерировать, должно быть в репозитории?

2018-07-23 00:37 UTC, Tirraon commented
@ASbeletsky

2018-07-23 08:12 UTC, ASbeletsky approved these changes

2018-07-23 08:20 UTC, ASbeletsky commented
На счет кривого апдейта, я думаю это еф кор лажает, пусть будет как есть. Ченжи по UI и валидации выпишу отдельно. В целом мне нравиться, сделано хорошо, молодец.

2018-07-23 08:21 UTC, merged